### ISSUE TITLE
Implement cycle counts per instruction function

### ISSUE THREAD

**Issue by bobomb** [bittwiddler1/dNES#14]
Each instruction function needs to have a way to convey the number of cycles that instruction took.

http://www.obelisk.demon.co.uk/6502/reference.html#BMI

Should we return the # of cycles that have elapsed from each instruction function? so whatever is calling the instructions can count the cycles.

**Comment by s-daveb** [comment]
Using the function return types like that would be smart, I think we should go for it. Maybe this should  be listed as part of issues #7, #12,#13

**Comment by s-daveb** [comment]
I think we should close this now that we have cycle count tables in 6b51541360b72bb0bea46f5aa2a50ccd6e775ffa

Let me know what you think.

**Comment by bobomb** [comment]
Yeah, this is good to be closed now that we have the cycle count table.
