### ISSUE TITLE
status register is private but unit tests still pass?

### ISSUE THREAD

**Issue by bobomb** [bittwiddler1/dNES#2]
With commit 8e5f417ce0a3eca9ad00e1c5822639c0df53a7cb I've made the status register private however the unit tests are still accessing this private field via ._status.

**Comment by s-daveb** [comment]
D doesn't [quite work the same way as C++ ](http://wiki.dlang.org/Access_specifiers_and_visibility).

> Private means that only members of the enclosing class can access the member, or members andv functions in the same module as the enclosing class. Private members cannot be overridden.
> 
> dlang.org states that "Private module members are equivalent to static declarations in C programs." but this is wrong, they have external linkage:

The unit-tests are in the same module, so it's fine. I guess this means we really need to be careful about defining two classes in one module. They will automatically be  "friend classes".
