### ISSUE TITLE
Incorrect address mode, EOR, Indexed Indirect opcode 0x41

### ISSUE THREAD

**Issue by bobomb** [bittwiddler1/dNES#22]
I am looking at the docs for the EOR instruction:
`Address Mode    Syntax        Opcode  I-Len  T-Cnt  
  Immediate       EOR #$A5       $49      2     2   
  Zero Page       EOR $A5        $45      2     3   
  Zero Page,X     EOR $A5,X      $55      2     4   
  Absolute        EOR $A5B6      $4D      3     4   
  Absolute,X      EOR $A5B6,X    $5D      3     4+  
  Absolute,Y      EOR $A5B6,Y    $59      3     4+  
  (Indirect,X)    EOR ($A5,X)    $41      2     6   <---- indexed indirect
  (Indirect),Y    EOR ($A5),Y    $51      2     5+`

Table lookup for opcode 0x41 in the addressmodetable resolves to a value of 0xF1. This is incorrect, as the enum states         INDEXED_INDIRECT = 0xF1, // INDIRECT_X

Verify please?

**Comment by s-daveb** [comment]
INDIRECT_X and INDIRECT_INDEXED are names for the same thing

**Comment by s-daveb** [comment]
http://emulator101.com/6502-addressing-modes/

Read about how indirect_indexed  works. It uses the X registee. Infexed_indirect uses the y register

**Comment by bobomb** [comment]
I made an error: the problem is still real.
The table:
`//  0      1      2      3      4      5      6      7  
         //  8      9      A      B      C      D      E      F    

0x01,  0xF2,  0x00,  0xF2,  0xB0,  0xB0,  0xB0,  0xB0, // 4
          0x01,  0x10,  0xA0,  0x00,  0xD0,  0xD0,  0xD0,  0xD0, // 4`

Entry for 0x41 is 0xF2 which is incorrect.

**Comment by bobomb** [comment]
fixed with commit 9e72619
