### ISSUE TITLE
Addressing mode data fetching functions

### ISSUE THREAD

**Issue by s-daveb** [bittwiddler1/dNES#6]
As we discussed over burritos, we will need functions that return references to bytes or byte arrays when given proper inputs from the CPU instruction decoder.

This will enable us to "generally"  implement each instruction once, and to fetch its input parameter in various different ways.

I will fill in more details later, but as of now, say we encounter the instruciton opcode `$69`.
Our Instruction decoding function should be able to recognize that as `ADC` "Add with Carry" , using the immediate "addressing" mode, interpreting the next character as an 8-bit constant. `$65` would be interpreted as `ADC` in "zero page" mode, which would result in the next byte being interpreted as an 8-bit address in the first 256 butes of memory.

Hence, 

``` ASM
ADC  #$10 ;  Add  a literal, decimal 17 to the accumulator 
ADC  $10  ;  Add the contents of the byte at address $10 to the accumulator
```

which would be assembled to 

```
$69 $10
$65 $10
```

There is a reference of all the addressing modes [here](http://www.obelisk.demon.co.uk/6502/addressing.html#IMM)

**Comment by bobomb** [comment]
I've implemented two of the functions so far with commit 87a6a886685bc87ebd9656ed42261f4b84420633

**Comment by bobomb** [comment]
Some notes: http://www.dwheeler.com/6502/oneelkruns/asm1step.html mentions that indirect indexed and indxed indirect read 16 bit addresses

**Comment by bobomb** [comment]
All thats left to implement is indirect indexed addressing mode

**Comment by bobomb** [comment]
With 3d0e302 we've implemented the full set of address modes:
- Immediate
- Absolute
- Zero Page
- Indirect (aka indirect absolute)
- Absolute Indexed
- Zero Page Indexed
- Indexed Indirect
- Indirect Indexed
- Relative
  There are probably edge cases to our implementations that may not be correct, those will be fixed as we find them.
